---
swagger: "2.0"
info:
  description: "This is a sample Domain Service.  You can find \nout more about Swagger at \n[http://swagger.io](http://swagger.io) or on \n[irc.freenode.net, #swagger](http://swagger.io/irc/).\n"
  version: 1.0.0
  title: Swagger Domain Service
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: virtserver.swaggerhub.com
basePath: /marcus-n3rd/domain-service/1.0.0
tags:
- name: domain
  description: Everything about your Domains
  externalDocs:
    description: Find out more
    url: http://swagger.io
schemes:
- https
- http
paths:
  /domains/{id}:
    get:
      tags:
      - domains
      summary: Find domain by ID
      description: Returns a single domain
      operationId: getDomainById
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: ID of domain to return
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: successful operation
          schema:
            $ref: '#/definitions/Domain'
        "400":
          description: Invalid ID supplied
        "404":
          description: Domain not found
      security:
      - api_key: []
    put:
      tags:
      - domain
      summary: Updates a domain in the store with form data
      operationId: updatePetWithForm
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        description: ID of domain that needs to be updated
        required: true
        type: integer
        format: int64
      - name: name
        in: formData
        description: Updated name of the domain
        required: false
        type: string
      - name: status
        in: formData
        description: Updated status of the domain
        required: false
        type: string
      responses:
        "405":
          description: Invalid input
      security:
      - bearer_auth:
        - write:domains
        - read:domains
securityDefinitions:
  bearer_auth:
    type: oauth2
    authorizationUrl: http://petstore.swagger.io/oauth/dialog
    flow: implicit
    scopes:
      write:domains: modify domains in your account
      read:domains: read your domains
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Tag:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    xml:
      name: Tag
  Domain:
    type: object
    required:
    - name
    properties:
      id:
        type: integer
        format: int64
      category:
        $ref: '#/definitions/Category'
      name:
        type: string
        example: foobar
      tags:
        type: array
        xml:
          name: tag
          wrapped: true
        items:
          $ref: '#/definitions/Tag'
      status:
        type: string
        description: domain status in the store
        enum:
        - available
        - pending
        - sold
    xml:
      name: Domain
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
